window.DDAS_DATA = {
  datasets: [
    {
      id: "DDAS-CLIM-ERA5-02491",
      title: "ERA5 India Hourly Rainfall — 2024",
      description: "Hourly precipitation and surface variables covering the Indian subcontinent.",
      provider: "ECMWF Copernicus CDS",
      family: "ERA5 Reanalysis",
      format: "NetCDF4 / CF-1.7",
      size: "32.8 GB",
      sizeGB: 32.8,
      source: "ECMWF / CDS",
      location: "Climate Node 03",
      storagePath: "s3://institute-climate/node-03/era5/2024/india/",
      accessPath: "/mnt/research/climate/era5/2024/india/",
      owner: "Climate Analytics Group",
      downloader: "R. Kulkarni",
      downloadedOn: "17 Feb 2025 · 03:14 IST",
      lastAccessed: "18 Aug 2026 · 16:42 IST",
      access: "Institute-wide",
      license: "Copernicus C3S",
      reuseCount: 143,
      activeUsers: 27,
      hash: "8f51d9a7c2e11b56a00d73df6e61dc277c9851ec...1c7e94bf",
      simhash: "simhash:9a82f31c",
      mime: "application/x-netcdf",
      version: "v3.2 · immutable",
      period: "01 Jan–31 Dec 2024",
      startYear: 2024,
      endYear: 2024,
      temporalResolution: "Hourly",
      region: "India",
      latitude: "6.0°N → 37.5°N",
      longitude: "68.0°E → 97.5°E",
      resolution: "0.25° × 0.25°",
      crs: "EPSG:4326 / WGS84",
      variables: ["total_precipitation", "temperature_2m", "surface_pressure", "dewpoint_2m"],
      tags: ["rainfall", "precipitation", "climate", "reanalysis", "india", "era5"],
      type: "Climate",
      match: 98,
      integrity: "Verified 18 Aug 2026",
      replicas: 2,
      storageTier: "Hot",
      color: "accent"
    },
    {
      id: "DDAS-MON-00942",
      title: "Monsoon Research Cube — West India 2023–25",
      description: "Preprocessed rainfall, humidity and pressure cube for western India.",
      provider: "Institute Climate Lab",
      family: "Monsoon Composite",
      format: "Zarr",
      size: "18.2 GB",
      sizeGB: 18.2,
      source: "IMD + ERA5",
      location: "Geo Lab NAS",
      storagePath: "nas://geo-lab/monsoon/west-india-2023-25/",
      accessPath: "/mnt/geo/monsoon/west-india/",
      owner: "Geo Analytics Lab",
      downloader: "A. Shah",
      downloadedOn: "02 Jun 2025 · 11:25 IST",
      lastAccessed: "17 Aug 2026 · 19:22 IST",
      access: "Lab owned",
      license: "Research internal",
      reuseCount: 76,
      activeUsers: 14,
      hash: "2db1c95124e093f0...129cf9a7",
      simhash: "simhash:de3fa11c",
      mime: "application/vnd+zarr",
      version: "v2.4",
      period: "01 Jan 2023–31 Dec 2025",
      startYear: 2023,
      endYear: 2025,
      temporalResolution: "Daily",
      region: "West India",
      latitude: "8.0°N → 28.0°N",
      longitude: "68.0°E → 80.5°E",
      resolution: "0.10° × 0.10°",
      crs: "EPSG:4326 / WGS84",
      variables: ["rainfall", "humidity", "surface_pressure"],
      tags: ["monsoon", "rainfall", "west india", "imd", "era5"],
      type: "Climate",
      match: 91,
      integrity: "Verified 17 Aug 2026",
      replicas: 1,
      storageTier: "Hot",
      color: "mint"
    },
    {
      id: "DDAS-IMD-44110",
      title: "District Rainfall Aggregates — Maharashtra",
      description: "District-wise daily rainfall aggregates prepared for regional analysis.",
      provider: "India Meteorological Department",
      family: "District Rainfall",
      format: "CSV",
      size: "712 MB",
      sizeGB: 0.712,
      source: "IMD",
      location: "DataHub 01",
      storagePath: "s3://datahub-01/imd/maharashtra/district-rainfall/",
      accessPath: "/mnt/datahub/imd/maharashtra/rainfall/",
      owner: "Earth Science Repository",
      downloader: "S. Patil",
      downloadedOn: "06 Jan 2025 · 14:10 IST",
      lastAccessed: "18 Aug 2026 · 11:09 IST",
      access: "Public institute",
      license: "IMD data policy",
      reuseCount: 219,
      activeUsers: 41,
      hash: "cc7f0c0f732501aa...31ea8f2a",
      simhash: "simhash:8724cc03",
      mime: "text/csv",
      version: "2024-final",
      period: "01 Jan–31 Dec 2024",
      startYear: 2024,
      endYear: 2024,
      temporalResolution: "Daily",
      region: "Maharashtra",
      latitude: "15.6°N → 22.1°N",
      longitude: "72.6°E → 80.9°E",
      resolution: "District aggregated",
      crs: "EPSG:4326 / WGS84",
      variables: ["rainfall_mm", "district", "date"],
      tags: ["maharashtra", "rainfall", "district", "imd"],
      type: "Climate",
      match: 82,
      integrity: "Verified 18 Aug 2026",
      replicas: 2,
      storageTier: "Warm",
      color: "sky"
    },
    {
      id: "DDAS-RS-S2-11384",
      title: "Sentinel-2 L2A Mumbai Metropolitan Region",
      description: "Cloud-filtered Sentinel-2 imagery for Mumbai and surrounding coastal areas.",
      provider: "Copernicus Data Space",
      family: "Sentinel-2 L2A",
      format: "COG / GeoTIFF",
      size: "64.5 GB",
      sizeGB: 64.5,
      source: "ESA Copernicus",
      location: "Remote Sensing Node 02",
      storagePath: "s3://rs-node-02/sentinel2/mumbai/2025/",
      accessPath: "/mnt/rs/sentinel2/mumbai/2025/",
      owner: "Remote Sensing Division",
      downloader: "N. Iyer",
      downloadedOn: "28 Nov 2025 · 08:41 IST",
      lastAccessed: "18 Aug 2026 · 17:03 IST",
      access: "Institute-wide",
      license: "Copernicus open data",
      reuseCount: 188,
      activeUsers: 32,
      hash: "collection:8b70c2...sentinel2-mum",
      simhash: "simhash:44ad91de",
      mime: "image/tiff; application=geotiff",
      version: "collection-r12",
      period: "01 Jan–31 Dec 2025",
      startYear: 2025,
      endYear: 2025,
      temporalResolution: "5-day revisit",
      region: "Mumbai Metropolitan Region",
      latitude: "18.7°N → 19.6°N",
      longitude: "72.6°E → 73.4°E",
      resolution: "10 m / 20 m / 60 m",
      crs: "UTM 43N / WGS84",
      variables: ["B02", "B03", "B04", "B08", "SCL"],
      tags: ["sentinel", "satellite", "mumbai", "remote sensing", "imagery"],
      type: "Remote Sensing",
      match: 77,
      integrity: "Verified 18 Aug 2026",
      replicas: 2,
      storageTier: "Hot",
      color: "violet"
    },
    {
      id: "DDAS-OCEAN-77214",
      title: "Arabian Sea SST — 2021–2025",
      description: "Sea surface temperature timeseries and gridded composites across the Arabian Sea.",
      provider: "NOAA + GHRSST",
      family: "Sea Surface Temperature",
      format: "NetCDF",
      size: "21.6 GB",
      sizeGB: 21.6,
      source: "GHRSST",
      location: "Ocean Node 05",
      storagePath: "s3://ocean-node-05/sst/arabian-sea/2021-2025/",
      accessPath: "/mnt/ocean/sst/arabian-sea/",
      owner: "Ocean Sciences Lab",
      downloader: "P. Menon",
      downloadedOn: "14 Jan 2026 · 06:50 IST",
      lastAccessed: "18 Aug 2026 · 16:10 IST",
      access: "Approval required",
      license: "GHRSST open + internal processing",
      reuseCount: 58,
      activeUsers: 12,
      hash: "83bb8a70534fc1e9...2100bc21",
      simhash: "simhash:aa70f9d2",
      mime: "application/x-netcdf",
      version: "v1.9",
      period: "01 Jan 2021–31 Dec 2025",
      startYear: 2021,
      endYear: 2025,
      temporalResolution: "Daily",
      region: "Arabian Sea",
      latitude: "5°N → 25°N",
      longitude: "50°E → 80°E",
      resolution: "0.05° × 0.05°",
      crs: "EPSG:4326 / WGS84",
      variables: ["sea_surface_temperature", "quality_level", "sst_dtime"],
      tags: ["ocean", "sst", "arabian sea", "ghrsst", "temperature"],
      type: "Oceanography",
      match: 74,
      integrity: "Verified 16 Aug 2026",
      replicas: 1,
      storageTier: "Warm",
      color: "sky"
    },
    {
      id: "DDAS-CENSUS-2021-118",
      title: "Population & Demographic Census Extracts",
      description: "District-level demographic indicators prepared for multidisciplinary research use.",
      provider: "Institute Data Services",
      family: "Census & Demography",
      format: "Parquet",
      size: "4.8 GB",
      sizeGB: 4.8,
      source: "Census repository",
      location: "Social Data Node 04",
      storagePath: "s3://social-node-04/census/district-extracts/",
      accessPath: "/mnt/social/census/district/",
      owner: "Data Services Unit",
      downloader: "M. Rao",
      downloadedOn: "11 Sep 2025 · 10:20 IST",
      lastAccessed: "16 Aug 2026 · 13:02 IST",
      access: "Institute-wide",
      license: "Internal research use",
      reuseCount: 102,
      activeUsers: 19,
      hash: "4c2a76c04012...4a927c91",
      simhash: "simhash:4d110a30",
      mime: "application/vnd.apache.parquet",
      version: "rev-5",
      period: "2011–2021 reference periods",
      startYear: 2011,
      endYear: 2021,
      temporalResolution: "Census / survey",
      region: "India",
      latitude: "Pan-India",
      longitude: "Pan-India",
      resolution: "District",
      crs: "Administrative boundaries",
      variables: ["population", "age", "sex_ratio", "literacy", "households"],
      tags: ["census", "population", "demography", "district"],
      type: "Demography",
      match: 51,
      integrity: "Verified 12 Aug 2026",
      replicas: 2,
      storageTier: "Warm",
      color: "gold"
    }
  ],
  activities: [
    {type:"prevented", icon:"⚡", title:"Duplicate prevented · Sentinel-2 L2A Mumbai", detail:"Existing copy served from Remote Sensing Node 02", time:"2m", user:"D. Kulkarni", saved:"11.2 GB"},
    {type:"request", icon:"↗", title:"Access requested · Arabian Sea SST 2021–25", detail:"Request routed to Ocean Sciences Lab", time:"18m", user:"M. Desai", saved:"—"},
    {type:"indexed", icon:"＋", title:"New dataset indexed · MODIS Aerosol Daily", detail:"SHA-256 + spatial metadata extraction complete", time:"41m", user:"System", saved:"—"},
    {type:"prevented", icon:"⚡", title:"Duplicate prevented · ERA5 Maharashtra subset", detail:"Request satisfied from ERA5 India 2024 archive", time:"1h", user:"A. Mehta", saved:"8.4 GB"},
    {type:"override", icon:"↓", title:"Download override · Landsat 9 Pune tile", detail:"User selected different atmospheric correction requirement", time:"2h", user:"S. Jain", saved:"0 GB"},
    {type:"indexed", icon:"＋", title:"New dataset indexed · District Groundwater Levels", detail:"Repository scan completed on Hydro Node 06", time:"3h", user:"Indexer", saved:"—"},
    {type:"prevented", icon:"⚡", title:"Duplicate prevented · IMD District Rainfall", detail:"Existing 2024 CSV reused by Environment Lab", time:"4h", user:"P. Shah", saved:"712 MB"},
    {type:"request", icon:"↗", title:"Access approved · High-resolution bathymetry", detail:"Owner approved research group access", time:"5h", user:"Admin", saved:"—"}
  ],
  stats: {
    prevented: 829,
    storageTB: 4.31,
    bandwidthTB: 3.74,
    datasets: 12428,
    repositories: 16,
    users: 684,
    reuseRate: 68,
    monthlyPrevented: [42,55,61,58,74,79,88,93,86,104,117,132],
    monthlyStorage: [0.18,0.24,0.27,0.31,0.29,0.34,0.38,0.42,0.47,0.43,0.51,0.58],
    departments: [
      {name:"Climate Analytics", value:31},
      {name:"Remote Sensing", value:24},
      {name:"Ocean Sciences", value:18},
      {name:"Environmental Research", value:14},
      {name:"Other", value:13}
    ]
  }
};
